//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickSearch.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SearchInTitle {
            get {
                return ((bool)(this["SearchInTitle"]));
            }
            set {
                this["SearchInTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SearchInUrl {
            get {
                return ((bool)(this["SearchInUrl"]));
            }
            set {
                this["SearchInUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchCaseSensitive {
            get {
                return ((bool)(this["SearchCaseSensitive"]));
            }
            set {
                this["SearchCaseSensitive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("228, 160, 143")]
        public global::System.Drawing.Color BackColorOnError {
            get {
                return ((global::System.Drawing.Color)(this["BackColorOnError"]));
            }
            set {
                this["BackColorOnError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FocusOnOpen {
            get {
                return ((bool)(this["FocusOnOpen"]));
            }
            set {
                this["FocusOnOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchInPassword {
            get {
                return ((bool)(this["SearchInPassword"]));
            }
            set {
                this["SearchInPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchInUserName {
            get {
                return ((bool)(this["SearchInUserName"]));
            }
            set {
                this["SearchInUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchInNotes {
            get {
                return ((bool)(this["SearchInNotes"]));
            }
            set {
                this["SearchInNotes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchInGroupName {
            get {
                return ((bool)(this["SearchInGroupName"]));
            }
            set {
                this["SearchInGroupName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchExcludeExpired {
            get {
                return ((bool)(this["SearchExcludeExpired"]));
            }
            set {
                this["SearchExcludeExpired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchInOther {
            get {
                return ((bool)(this["SearchInOther"]));
            }
            set {
                this["SearchInOther"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowQuickFind {
            get {
                return ((bool)(this["ShowQuickFind"]));
            }
            set {
                this["ShowQuickFind"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("204, 201, 145")]
        public global::System.Drawing.Color BackColorSearching {
            get {
                return ((global::System.Drawing.Color)(this["BackColorSearching"]));
            }
            set {
                this["BackColorSearching"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("216, 233, 214")]
        public global::System.Drawing.Color BackColorSuccess {
            get {
                return ((global::System.Drawing.Color)(this["BackColorSuccess"]));
            }
            set {
                this["BackColorSuccess"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color BackColorNormalUnFocused {
            get {
                return ((global::System.Drawing.Color)(this["BackColorNormalUnFocused"]));
            }
            set {
                this["BackColorNormalUnFocused"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 255, 206")]
        public global::System.Drawing.Color BackColorNormalFocused {
            get {
                return ((global::System.Drawing.Color)(this["BackColorNormalFocused"]));
            }
            set {
                this["BackColorNormalFocused"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int ControlWidth {
            get {
                return ((int)(this["ControlWidth"]));
            }
            set {
                this["ControlWidth"] = value;
            }
        }
    }
}
